spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagerdb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 14400000

